### ISSUE TITLE
Deprecated core-js@2.6.12: core-js@<3.23.3 - Warning

### ISSUE THREAD

**Issue by ampedweb** [zackad/prettier-plugin-twig#34]
It's pretty much summarised in the title, and I'm sure you're aware of it, but it would be good to get the following dependencies upgraded as it's locking us to a very outdated `core-js:2.6.12` version.

```json
{
        "babel-template": "^6.26.0",
        "babel-types": "^6.26.0",
} 
```

**Comment by ampedweb** [comment]
@zackad Would it be possible for you to create a release for this please? We'd like to remove this deprecation if possible :-)

**Comment by zackad** [comment]
The plan is to release this package under the new name `@zackad/prettier-plugin-twig`[0]. As you can see in the README.md, it's not ready yet. I have lots of BREAKING CHANGE I want to introduce. Something that I haven't done yet is renaming the parser/AST from `melody` -> `twig` to clarify that this project if focusing on twig formatting and nothing else. This change will break compatibility with other prettier plugin such as `prettier-plugin-tailwindcss`[1].

Ref: 
[0]: https://www.npmjs.com/package/@zackad/prettier-plugin-twig
[1]: https://github.com/tailwindlabs/prettier-plugin-tailwindcss
