### ISSUE TITLE
Tests can't be configured with prettier options on a per-test basis

### ISSUE THREAD

**Issue by rellafella** [zackad/prettier-plugin-twig#43]
An updated system that doesn't rely on snapshots but rather the comparison of 2 files.

A few benefits of this include:
- tests can be configured with different prettier options on a per-test basis
- the formatted and unformatted version would both be in a twig file so is more easy to read by humans
- if tests are easier to write/interpret then hopefully collaboration is easier too

Whilst this project is completely written in typescript what they have done with their tests is very easy to follow.
https://github.com/prettier/plugin-pug

Happy to start working on a PR for this if you think it is worth it

**Comment by zackad** [comment]
Interesting approach. I'd love to see it being implemented.
