### ISSUE TITLE
[FR] Add support for custom tests in Twig

### ISSUE THREAD

**Issue by rungta** [zackad/prettier-plugin-twig#45]
Twig allows custom test operators to be defined which is leveraged by Craft CMS to include [tests like `instance of`](https://craftcms.com/docs/5.x/reference/twig/tests.html#instance-of).

Would be great to have support for declaring these as an option similar to `twigMultiTags`.

### Stack Trace

```
templates/_routers/collective.twig
[error] templates/_routers/collective.twig: Error: ERROR: Unknown test "instance of"
[error]   3 | #}
[error]   4 | 
[error] > 5 | {%- extends (element is instance of ('craft\\elements\\Category') ? [
[error]     |                         ^
[error]   6 |   '_views/collectives/' ~ element.group.handle,
[error]   7 | ] : [
[error]     at TokenStream.error (file:///.../node_modules/@zackad/prettier-plugin-twig/src/melody/melody-parser/TokenStream.js:129:24)
[error]     at Parser.error (file:///.../node_modules/@zackad/prettier-plugin-twig/src/melody/melody-parser/Parser.js:452:21)
[error]     at getTest (file:///.../node_modules/@zackad/prettier-plugin-twig/src/melody/melody-extension-core/operators.js:258:20)
[error]     at Object.parse (file:///.../node_modules/@zackad/prettier-plugin-twig/src/melody/melody-extension-core/operators.js:226:22)
[error]     at Parser.matchExpression (file:///.../node_modules/@zackad/prettier-plugin-twig/src/melody/melody-parser/Parser.js:532:27)
[error]     at Parser.getPrimary (file:///.../node_modules/@zackad/prettier-plugin-twig/src/melody/melody-parser/Parser.js:577:31)
```

**Comment by aarongerig** [comment]
@zackad While this case "instance of" has been resolved, I have many other custom tests, that I have implemented in my (Pimcore) projects. Unfortunately, I cannot register those tests. I would like to be able to register them kinda like with the option "twigMultiBlock", where I'm able to list any custom nodes/tags.

Here are some examples:
- [Document tests](https://github.com/pimcore/pimcore/blob/12.x/lib/Twig/Extension/DocumentHelperExtensions.php)
- [Data Object tests](https://github.com/pimcore/pimcore/blob/12.x/lib/Twig/Extension/DataObjectHelperExtensions.php)
- [Asset tests](https://github.com/pimcore/pimcore/blob/12.x/lib/Twig/Extension/AssetHelperExtensions.php)

I also have some custom one's, which are not listed in this repository. Any idea how to add support?

This is the error message that I see:
```bash
templates/my_twig_file.html.twig: Error: ERROR: Invalid Token
[error]   19 |                 </ul>
[error]   20 |             {% endif %}
[error] > 21 |             {% if news_page is pimcore_document_page %}
[error]      |                                                      ^^
[error] 
[error] Expected symbol but found tag end "%}" instead.
```

**Comment by zackad** [comment]
The easiest solution I can think is by adding all test expression into operator declaration inside this file.

https://github.com/zackad/prettier-plugin-twig/blob/758e4fd5366d0a497e55e6c72be3b5703484fe94/src/melody/melody-extension-core/operators.js#L349-L380

But I don't think this is a scalable solution. Best solution is to add new feature that allow end user to register custom test expression like your suggestion. Would you like to give it a try?

PS: please refrain commenting on closed issue/pr. Open new issue and reference to related issue/pr. Thanks.

**Comment by aarongerig** [comment]
@zackad Sorry, my bad --> https://github.com/zackad/prettier-plugin-twig/issues/116
