### ISSUE TITLE
The parser does not keep the false value of the autoescape tag

### ISSUE THREAD

**Issue by RamBoFe** [zackad/prettier-plugin-twig#63]
Instead, the parser sets the value to 'html'.

To reproduce the behavior, use this code line : 

```twig
{% autoescape false %}
    Everything will be outputted as is in this block
{% endautoescape %}
``` 

After formatting, I end up with this : 

```twig
{% autoescape 'html' %}
    Everything will be outputted as is in this block
{% endautoescape %}
``` 

I think this behavior is not correct. We should keep the value false. What do you think ?

**Comment by zackad** [comment]
To be honest, I never use this feature and have no idea how they should behave. But looking at the documentation[1], `false` is indeed a valid value.

Reference:
[1]: https://twig.symfony.com/doc/3.x/tags/autoescape.html

**Comment by zackad** [comment]
Possible cause
https://github.com/zackad/prettier-plugin-twig/blob/bd69277bad70d5bf9c46ff9ccbeb3ff75407c6f4/src/print/AutoescapeBlock.js#L11

**Comment by RamBoFe** [comment]
Yes, according to the documentation, the value false is correct. This is why i said that I think this behavior is not correct. Why change the value false to 'html' when the documentation clearly states that the value false is one of the possible values ​​of the autoescape tag ?
