### ISSUE TITLE
Default arguments in macros aren't supported

### ISSUE THREAD

**Issue by lexisother** [zackad/prettier-plugin-twig#69]
Same issue as here: https://github.com/trivago/prettier-plugin-twig-melody/issues/42

**Comment by zackad** [comment]
Ref: https://twig.symfony.com/doc/3.x/tags/macro.html

**Comment by zackad** [comment]
Hi @lexisother, could you provide some example of how the syntax looks like? Maybe with some variation. Or the example from documentation is enough? I never use macros.

Thanks.

**Comment by lexisother** [comment]
Hi,

Here's the macro the parser is failing on:
```twig
{% macro hosted(fontFamily, filenameWithoutExt = false, fontWeight = '400', fontStyle = 'normal', preload = false) %}
```

**Comment by zackad** [comment]
Hi @lexisother,

I've create #70 that should add support for default value of macros. Would like to hear your feedback on this feature. You can follow this guide to install non-released version. Just make sure to change branch name into `GH-69/macros-arguments`.

https://github.com/zackad/prettier-plugin-twig/issues/66#issuecomment-2403687031

Thanks.
